### ISSUE TITLE
Cannot decode captured video file

### ISSUE THREAD

**Issue by kunguz** [6by9/raspiraw#10]
Hi,

I am having this trouble in decoding the capture data to a video file on my raspberry pi zero w. 

This is what I got in the bash:
```
pi@muska:~/raspiraw/tools $ ./320x240 1000
removing /dev/shm/out.*.raw
capturing frames for 1000ms with 180fps requested
180 frames were captured at 180fps
frame delta time[us] distribution
      1 
      6 5544
     92 5545
     76 5546
      5 5547
after skip frame indices (middle column)
0% frame skips
pi@muska:~/raspiraw/tools $ ./raw2ogg2anim hd0.32k 0 10 180 file.ogg
removing old auxiliary files
copying /dev/shm/out.????.raw files
cat: /dev/shm/out.0000.raw: No such file or directory
10     
dcraw each .raw file (to .ppm)
Cannot decode file out.0000.raw
Cannot decode file out.0001.raw
Cannot decode file out.0002.raw
Cannot decode file out.0003.raw
Cannot decode file out.0004.raw
Cannot decode file out.0005.raw
Cannot decode file out.0006.raw
Cannot decode file out.0007.raw
Cannot decode file out.0008.raw
Cannot decode file out.0009.raw
Cannot decode file out.0010.raw
out.0010.raw     
.ppm -> .ppm.d
double: double.c:11: main: Assertion `src' failed.
./raw2ogg2anim: line 28:  5407 Aborted                 double $f > $f.D
double: double.c:12: main: Assertion `0 == strcmp(line, "P6\n") || 0 == strcmp(line, "P5\n")' failed.
./raw2ogg2anim: line 28:  5408 Aborted                 double $f.D > $f.d
out.*.ppm     
.ppm.d -> .ppm.d.png
./raw2ogg2anim: line 47: pnmtopng: command not found
out.*.ppm.d     
now creating hd0.32k.ogg
./raw2ogg2anim: line 53: gst-launch-1.0: command not found
now creating hd0.32k.anim.gif
/home/pi/raspiraw/tools/gifenc.sh: 11: /home/pi/raspiraw/tools/gifenc.sh: ffmpeg: not found
/home/pi/raspiraw/tools/gifenc.sh: 12: /home/pi/raspiraw/tools/gifenc.sh: ffmpeg: not found
```

May I kindly get your help when you get a chance to reply?

Thanks!
Kaan

**Comment by 6by9** [comment]
All those scripts have been written by @Hermann-SW.

The first issue appears to be that you haven't installed half the required tools
```sudo apt install netpbm ffmpeg gstreamer-tools``` may help for part of it. I haven't looked into which bits of GStreamer are being used, so you may need various additional packages there.

**Comment by Hermann-SW** [comment]
I agree with 6by9 that needed tools have not been installed (ffmpeg).

The output above is badly readable, should have pasted into a code block.
I reformatted and the capturing was successful (180 frames captured in 1s, no frame skips):
`pi@muska:&#126;/raspiraw/tools $ ./320x240 1000
removing /dev/shm/out.*.raw
capturing frames for 1000ms with 180fps requested
180 frames were captured at 180fps
frame delta time[us] distribution
1 
6 5544 
92 5545 
76 5546 
5 5547
after skip frame indices (middle column)
0% frame skips
pi@muska:~/raspiraw/tools $

`


Readme.md clearly mentions that gstreamer is used:
[https://github.com/6by9/raspiraw](https://github.com/6by9/raspiraw)

In addition documentation on raw2ogg2anim there mentions ffmpeg and gifenc.sh as needed.

**Comment by kunguz** [comment]
Here is an update after installing ffmpeg, gstreamer-tools, netpbm. I can now see some more lines printed to the shell during a capture process, but result is more or less the same. The raw files aren't decoded.
``
pi@muska:~/raspiraw/tools $ ./320x240 1000
removing /dev/shm/out.*.raw
capturing frames for 1000ms with 180fps requested
ls: cannot access '/dev/shm/out.*.raw': No such file or directory
0 frames were captured at 332fps
frame delta time[us] distribution
      1 
      6 3003
      8 3004
    137 3005
    166 3006
      6 3007
      8 3008
after skip frame indices (middle column)
3006,2,1333811159
3005,3,1333814164
3005,4,1333817169
3006,5,1333820175
3008,6,1333823183
3003,7,1333826186
3006,8,1333829192
3005,9,1333832197
3006,10,1333835203
3007,11,1333838210
3004,12,1333841214
3005,13,1333844219
3006,14,1333847225
3005,15,1333850230
3006,16,1333853236
3006,17,1333856242
3005,18,1333859247
3006,19,1333862253
3005,20,1333865258
3006,21,1333868264
3005,22,1333871269
3006,23,1333874275
3005,24,1333877280
3006,25,1333880286
3006,26,1333883292
3005,27,1333886297
3006,28,1333889303
3005,29,1333892308
3006,30,1333895314
3005,31,1333898319
3008,32,1333901327
3003,33,1333904330
3006,34,1333907336
3005,35,1333910341
3006,36,1333913347
3006,37,1333916353
3005,38,1333919358
3008,39,1333922366
3004,40,1333925370
3005,41,1333928375
3005,42,1333931380
3006,43,1333934386
3006,44,1333937392
3005,45,1333940397
3005,46,1333943402
3006,47,1333946408
3006,48,1333949414
3005,49,1333952419
3006,50,1333955425
3005,51,1333958430
3006,52,1333961436
3005,53,1333964441
3006,54,1333967447
3006,55,1333970453
3005,56,1333973458
3006,57,1333976464
3005,58,1333979469
3006,59,1333982475
3005,60,1333985480
3006,61,1333988486
3006,62,1333991492
3005,63,1333994497
3006,64,1333997503
3007,65,1334000510
3004,66,1334003514
3005,67,1334006519
3006,68,1334009525
3005,69,1334012530
3006,70,1334015536
3005,71,1334018541
3006,72,1334021547
3005,73,1334024552
3006,74,1334027558
3006,75,1334030564
3005,76,1334033569
3005,77,1334036574
3006,78,1334039580
3006,79,1334042586
3007,80,1334045593
3004,81,1334048597
3005,82,1334051602
3006,83,1334054608
3005,84,1334057613
3006,85,1334060619
3005,86,1334063624
3006,87,1334066630
3006,88,1334069636
3006,89,1334072642
3005,90,1334075647
3005,91,1334078652
3006,92,1334081658
3006,93,1334084664
3005,94,1334087669
3006,95,1334090675
3005,96,1334093680
3006,97,1334096686
3005,98,1334099691
3006,99,1334102697
3005,100,1334105702
3006,101,1334108708
3005,102,1334111713
3006,103,1334114719
3005,104,1334117724
3006,105,1334120730
3006,106,1334123736
3005,107,1334126741
3006,108,1334129747
3005,109,1334132752
3007,110,1334135759
3006,111,1334138765
3004,112,1334141769
3006,113,1334144775
3005,114,1334147780
3006,115,1334150786
3005,116,1334153791
3006,117,1334156797
3005,118,1334159802
3006,119,1334162808
3005,120,1334165813
3006,121,1334168819
3005,122,1334171824
3006,123,1334174830
3005,124,1334177835
3008,125,1334180843
3003,126,1334183846
3006,127,1334186852
3006,128,1334189858
3005,129,1334192863
3006,130,1334195869
3006,131,1334198875
3005,132,1334201880
3006,133,1334204886
3006,134,1334207892
3005,135,1334210897
3005,136,1334213902
3006,137,1334216908
3006,138,1334219914
3005,139,1334222919
3006,140,1334225925
3005,141,1334228930
3008,142,1334231938
3004,143,1334234942
3005,144,1334237947
3005,145,1334240952
3006,146,1334243958
3006,147,1334246964
3005,148,1334249969
3006,149,1334252975
3005,150,1334255980
3006,151,1334258986
3005,152,1334261991
3006,153,1334264997
3006,154,1334268003
3005,155,1334271008
3005,156,1334274013
3006,157,1334277019
3006,158,1334280025
3005,159,1334283030
3006,160,1334286036
3006,161,1334289042
3006,162,1334292048
3005,163,1334295053
3005,164,1334298058
3005,165,1334301063
3006,166,1334304069
3005,167,1334307074
3006,168,1334310080
3005,169,1334313085
3006,170,1334316091
3005,171,1334319096
3006,172,1334322102
3005,173,1334325107
3006,174,1334328113
3006,175,1334331119
3005,176,1334334124
3005,177,1334337129
3006,178,1334340135
3006,179,1334343141
3007,180,1334346148
3004,181,1334349152
3005,182,1334352157
3006,183,1334355163
3005,184,1334358168
3006,185,1334361174
3005,186,1334364179
3006,187,1334367185
3006,188,1334370191
3005,189,1334373196
3006,190,1334376202
3005,191,1334379207
3006,192,1334382213
3005,193,1334385218
3006,194,1334388224
3005,195,1334391229
3006,196,1334394235
3005,197,1334397240
3006,198,1334400246
3006,199,1334403252
3005,200,1334406257
3006,201,1334409263
3008,202,1334412271
3003,203,1334415274
3006,204,1334418280
3005,205,1334421285
3006,206,1334424291
3005,207,1334427296
3006,208,1334430302
3005,209,1334433307
3006,210,1334436313
3006,211,1334439319
3005,212,1334442324
3005,213,1334445329
3006,214,1334448335
3005,215,1334451340
3006,216,1334454346
3006,217,1334457352
3005,218,1334460357
3006,219,1334463363
3005,220,1334466368
3006,221,1334469374
3006,222,1334472380
3005,223,1334475385
3005,224,1334478390
3006,225,1334481396
3006,226,1334484402
3005,227,1334487407
3006,228,1334490413
3005,229,1334493418
3006,230,1334496424
3005,231,1334499429
3006,232,1334502435
3005,233,1334505440
3006,234,1334508446
3006,235,1334511452
3005,236,1334514457
3006,237,1334517463
3005,238,1334520468
3006,239,1334523474
3005,240,1334526479
3006,241,1334529485
3005,242,1334532490
3006,243,1334535496
3005,244,1334538501
3006,245,1334541507
3006,246,1334544513
3005,247,1334547518
3006,248,1334550524
3005,249,1334553529
3006,250,1334556535
3005,251,1334559540
3006,252,1334562546
3006,253,1334565552
3005,254,1334568557
3006,255,1334571563
3005,256,1334574568
3005,257,1334577573
3006,258,1334580579
3006,259,1334583585
3005,260,1334586590
3006,261,1334589596
3005,262,1334592601
3006,263,1334595607
3005,264,1334598612
3006,265,1334601618
3006,266,1334604624
3005,267,1334607629
3005,268,1334610634
3006,269,1334613640
3006,270,1334616646
3005,271,1334619651
3006,272,1334622657
3005,273,1334625662
3006,274,1334628668
3005,275,1334631673
3006,276,1334634679
3006,277,1334637685
3005,278,1334640690
3006,279,1334643696
3006,280,1334646702
3005,281,1334649707
3005,282,1334652712
3006,283,1334655718
3005,284,1334658723
3006,285,1334661729
3006,286,1334664735
3005,287,1334667740
3006,288,1334670746
3005,289,1334673751
3006,290,1334676757
3005,291,1334679762
3006,292,1334682768
3006,293,1334685774
3005,294,1334688779
3005,295,1334691784
3006,296,1334694790
3006,297,1334697796
3005,298,1334700801
3006,299,1334703807
3005,300,1334706812
3006,301,1334709818
3005,302,1334712823
3006,303,1334715829
3005,304,1334718834
3006,305,1334721840
3006,306,1334724846
3005,307,1334727851
3006,308,1334730857
3005,309,1334733862
3006,310,1334736868
3007,311,1334739875
3004,312,1334742879
3005,313,1334745884
3008,314,1334748892
3003,315,1334751895
3006,316,1334754901
3006,317,1334757907
3005,318,1334760912
3006,319,1334763918
3006,320,1334766924
3005,321,1334769929
3005,322,1334772934
3006,323,1334775940
3006,324,1334778946
3005,325,1334781951
3005,326,1334784956
3006,327,1334787962
3006,328,1334790968
3005,329,1334793973
3008,330,1334796981
3003,331,1334799984
3006,332,1334802990
49% frame skips
pi@muska:~/raspiraw/tools $ ./raw2ogg2anim hd0.32k 0 10 180 file.ogg
removing old auxiliary files
copying /dev/shm/out.????.raw files
cat: /dev/shm/out.0000.raw: No such file or directory
cat: /dev/shm/out.0001.raw: No such file or directory
cat: /dev/shm/out.0002.raw: No such file or directory
cat: /dev/shm/out.0003.raw: No such file or directory
cat: /dev/shm/out.0004.raw: No such file or directory
cat: /dev/shm/out.0005.raw: No such file or directory
cat: /dev/shm/out.0006.raw: No such file or directory
cat: /dev/shm/out.0007.raw: No such file or directory
cat: /dev/shm/out.0008.raw: No such file or directory
cat: /dev/shm/out.0009.raw: No such file or directory
cat: /dev/shm/out.0010.raw: No such file or directory
10     
dcraw each .raw file (to .ppm)
Cannot decode file out.0000.raw
Cannot decode file out.0001.raw
Cannot decode file out.0002.raw
Cannot decode file out.0003.raw
Cannot decode file out.0004.raw
Cannot decode file out.0005.raw
Cannot decode file out.0006.raw
Cannot decode file out.0007.raw
Cannot decode file out.0008.raw
Cannot decode file out.0009.raw
Cannot decode file out.0010.raw
out.0010.raw     
.ppm -> .ppm.d
double: double.c:11: main: Assertion `src' failed.
./raw2ogg2anim: line 28:  8921 Aborted                 double $f > $f.D
double: double.c:12: main: Assertion `0 == strcmp(line, "P6\n") || 0 == strcmp(line, "P5\n")' failed.
./raw2ogg2anim: line 28:  8922 Aborted                 double $f.D > $f.d
out.*.ppm     
.ppm.d -> .ppm.d.png
pnmtopng: EOF / read error reading magic number
out.*.ppm.d     
now creating hd0.32k.ogg
./raw2ogg2anim: line 53: gst-launch-1.0: command not found
now creating hd0.32k.anim.gif
hd0.32k.ogg: No such file or directory
hd0.32k.ogg: No such file or directory
done

``

**Comment by Hermann-SW** [comment]
Not sure what you did. As I commented you successfully captured 180 frames the last time. This time you captured 0 frames. Most likely you executed raspivid or raspistill before, or restarted. In that case you need to cd into raspiraw folder and run ./camera_i2c.

You can avoid strikethrough in code by replacing "~" with "&#126;", tilde has special meaning in github.

This commandline is wrong as well:
`./raw2ogg2anim hd0.32k 0 10 180 file.ogg`

Tool tells you how to call
`$ raw2ogg2anim 
format: raw2ogg2anim vname first last fps [d[d]]
$ 

`

You should not overwrite the needed file hd0.32k.
This will create tst.ogg and tst.anim.gif, containg frames 1 to 10, playing at 180fps:
`./raw2ogg2anim tst 1 10 180`

Because of the temporary files created you should better work in a directory different to tools, tools directory need to be on $PATH.

**Comment by Hermann-SW** [comment]
What is size of hd0.32k for you? It should be 32KB:
`$ ls -l hd0.32k 
-rw-r--r-- 1 pi pi 32768 May 12 23:30 hd0.32k
$ 
`

**Comment by Hermann-SW** [comment]
From Readme.md -- you likely have not 6by9's version of dcraw:
The raw Bayer format frames captured by raspiraw can be converted to .ppm images by modified dcraw image processing app: https://github.com/6by9/dcraw

**Comment by kunguz** [comment]
I have added the tools to the bashrc,  and I have also cloned dcraw of 6by9 and run buildme right after installing dependencies

```
pi@muska:~/dcraw $ sudo apt-get install libjasper-dev libjpeg8-dev gettext liblcms2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libjasper1 libjpeg8
Suggested packages:
  gettext-doc autopoint libasprintf-dev libgettextpo-dev libjasper-runtime
The following NEW packages will be installed:
  gettext libjasper-dev libjasper1 libjpeg8 libjpeg8-dev liblcms2-dev
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,224 kB of archives.
After this operation, 13.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirror.us.leaseweb.net/raspbian/raspbian stretch/main armhf libjasper1 armhf 1.900.1-debian1-2.4+deb8u1 [110 kB]           
Get:2 http://mirrors.syringanetworks.net/raspbian/raspbian stretch/main armhf libjpeg8 armhf 8d1-2 [108 kB]                             
Get:3 http://raspbian.mirror.constant.com/raspbian stretch/main armhf gettext armhf 0.19.8.1-2 [1,434 kB]
Get:4 http://raspbian-us.ngc292.space/raspbian stretch/main armhf libjasper-dev armhf 1.900.1-debian1-2.4+deb8u1 [501 kB]                                    
Get:5 http://mirrors.syringanetworks.net/raspbian/raspbian stretch/main armhf libjpeg8-dev armhf 8d1-2 [205 kB]                              
Get:6 http://raspbian-us.ngc292.space/raspbian stretch/main armhf liblcms2-dev armhf 2.8-4 [4,866 kB]                                        
Fetched 7,224 kB in 6s (1,124 kB/s)                                                                                                                                                                                                           
Selecting previously unselected package libjasper1:armhf.
(Reading database ... 124556 files and directories currently installed.)
Preparing to unpack .../0-libjasper1_1.900.1-debian1-2.4+deb8u1_armhf.deb ...
Unpacking libjasper1:armhf (1.900.1-debian1-2.4+deb8u1) ...
Selecting previously unselected package libjpeg8:armhf.
Preparing to unpack .../1-libjpeg8_8d1-2_armhf.deb ...
Unpacking libjpeg8:armhf (8d1-2) ...
Selecting previously unselected package gettext.
Preparing to unpack .../2-gettext_0.19.8.1-2_armhf.deb ...
Unpacking gettext (0.19.8.1-2) ...
Selecting previously unselected package libjasper-dev.
Preparing to unpack .../3-libjasper-dev_1.900.1-debian1-2.4+deb8u1_armhf.deb ...
Unpacking libjasper-dev (1.900.1-debian1-2.4+deb8u1) ...
Selecting previously unselected package libjpeg8-dev:armhf.
Preparing to unpack .../4-libjpeg8-dev_8d1-2_armhf.deb ...
Unpacking libjpeg8-dev:armhf (8d1-2) ...
Selecting previously unselected package liblcms2-dev:armhf.
Preparing to unpack .../5-liblcms2-dev_2.8-4_armhf.deb ...
Unpacking liblcms2-dev:armhf (2.8-4) ...
Setting up liblcms2-dev:armhf (2.8-4) ...
Setting up libjasper1:armhf (1.900.1-debian1-2.4+deb8u1) ...
Setting up gettext (0.19.8.1-2) ...
Processing triggers for install-info (6.3.0.dfsg.1-1+b1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libjpeg8:armhf (8d1-2) ...
Setting up libjasper-dev (1.900.1-debian1-2.4+deb8u1) ...
Setting up libjpeg8-dev:armhf (8d1-2) ...
pi@muska:~/dcraw $ ./buildme 
/usr/bin/ld: warning: libjpeg.so.62, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libjasper.so, may conflict with libjpeg.so.8
```

and proceeded with the capture as in below:

```
pi@muska:~ $ camera_i2c 
setting GPIO for board revsion: 9000c1
PiZero W - I2C 0 on GPIO 28 & 29. GPIOs 40 & 44 for LED and power
pi@muska:~ $ raspiraw -md 7 -t 1000 -ts tstamps.csv -hd0 hd0.32k -h 64 --vinc 1F --fps 660 -r "380A,0040;3802,78;3806,0603" -sr 1 -o /dev/shm/out.%04d.raw 2>/dev/null
Using i2C device /dev/i2c-0
pi@muska:~ $ ls -l /dev/shm/out.*.raw | wc --lines
332
pi@muska:~ $ cat hd0.32k /dev/shm/out.0123.raw > out.0123.raw
pi@muska:~ $ cd dcraw/
pi@muska:~/dcraw $ ./dcraw ~/out.0123.raw 
pi@muska:~/dcraw $ double out.0123.ppm > out.0123.ppm.d
double: double.c:11: main: Assertion `src' failed.
Aborted
```

**Comment by Hermann-SW** [comment]
Ok, all sems to have worked for you.
Now you need to bring in bright light, otherwise you will see ferames like this.
You captured with 660fps, which leaves 1.6ms time for frames.
I used 1000lm light successfully up to 665fps.
For v2 camera 1000fps recording I have to use 5000lm very bright light, see:
[https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=212518&p=1310445#p1310442](https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=212518&p=1310445#p1310442)
My standard test object are some lego pieces with yellow, red, green, blue, white and block colors

**Comment by kunguz** [comment]
Got it, thanks for all the help. I will try the bright light addition when I get back to my home as I am doing all these on a remote raspberry pi at home.

**Comment by 6by9** [comment]
Closing issue as resolved.
