### ISSUE TITLE
Timestamp in tmpstamp.csv

### ISSUE THREAD

**Issue by nabbl** [6by9/raspiraw#12]
Hey there,

Might be a very stupid question but what kind of timestamp is saved into the csv?

e.g.: "90967194063"

**Comment by 6by9** [comment]
The raw microsecond STC (System Time Clock) timestamp from the VideoCore blocks.

**Comment by 6by9** [comment]
I'll assume this has answered your question, so closing. Please reopen if you have further questions on this subject.
