### ISSUE TITLE
ov5647 vts_reg_num_bits should be 15 bits

### ISSUE THREAD

**Issue by tmorley2000** [6by9/raspiraw#15]
vts_reg_num_bits is to to 10 bits in ov5647_modes.h, while this appears correct from the datasheet in the internet, the behavior of the PI firmware suggests it should be 15 bits.

Here is a section of a register capture from a 6 second exposure showing 0x380e/0x380f being set to 0x7f8c

 { 0x350a,0x0 },
 { 0x350b,0x10 },
 { 0x3212,0x0 },
 { 0x380e,0x7f },
 { 0x380f,0x8c },
 { 0x3500,0x7 },
 { 0x3501,0xf8 },
 { 0x3502,0x60 },
 { 0x3212,0x10 },
 { 0x3212,0xa0 },

**Comment by 6by9** [comment]
See https://github.com/6by9/raspiraw/pull/13
The VTS change is correct, but I still haven't had a chance to sanity check the gain changes. I'll merge the VTS one now.

**Comment by 6by9** [comment]
I've merged the VTS part of #13.
I've set it as 16 bits as that was what the PR had, and does concur with the OV5640 and OV5642 datasheets. I'm under NDA and therefore can not really discuss the details, and actually I don't believe I have that information to hand.
