### ISSUE TITLE
Update_regs() in raspiraw.c has some bugs.

### ISSUE THREAD

**Issue by GustavEngdahl** [6by9/raspiraw#17]
Hi,

I've got some fixes that I'd like to submit. 
Setting exposure and gain does not really work that well since the values written to registers are not correct.
Can someone give me permission to create a branch in the repo and I'll be able to create a pull request?

Regards,
Gustav

**Comment by 6by9** [comment]
Fork the project into your own account and commit your changes there. You can then create a PR which will request to merge the changes back into this repo.
https://help.github.com/articles/fork-a-repo/

**Comment by GustavEngdahl** [comment]
Ok, will do.

Thanks

Den fre 5 okt. 2018 kl 12:14 skrev 6by9 <notifications@github.com>:

**Comment by 6by9** [comment]
Closing as conversation gone to #18
