### ISSUE TITLE
Raspiraw: fps throttling at 120fps!

### ISSUE THREAD

**Issue by meq14xw** [6by9/raspiraw#23]
Hi, 

I ve been using raspiraw for a while. It was very good in spite of some instabilities. But just reinstalled os and the newest raspiraw few days earlier. 
here is the issue I posted with details and some test examples, just to save time. [forum link](https://lb.raspberrypi.org/forums/viewtopic.php?f=43&t=227284&p=1394611#p1394611)

Thank you very much.

**Comment by 6by9** [comment]
Answered on your forum post - you've filled the ramdisk.
