### ISSUE TITLE
Change FPS

### ISSUE THREAD

**Issue by AlexDupont93** [6by9/raspiraw#3]
Great work on this!!

When applying a mode to the camera, how can we set the frame rate? By default it seems to be the maximum FPS of the mode.

In the Datasheet I think it's says to change the clock divider to change the framerate. Do you know which register sets this? If example I want 10 FPS.

Thanks a lot for your great work.

Sincerely,
Alex

**Comment by 6by9** [comment]
Have a look at pull request #1. Hermann has done a fair amount of work which does add frame rate control and other things, but various chunks need some extra work before I'll merge them.

Leave the clock dividers alone unless you like a world of headaches.

**Comment by AlexDupont93** [comment]
Nice ! It works !

Thanks a lot 6by9 👍
