### ISSUE TITLE
240FPS on IMX477

### ISSUE THREAD

**Issue by huyleincepit** [6by9/raspiraw#80]
Hello,

I am currently developing an application that requires a high-speed camera. I am using IMX477 and Jetson Nano, but the Jetpack Driver only supports 60fps. I am attempting to achieve 1348x750 resolution at 240fps. I plan to update the Jetpack Driver, but I am unable to locate the datasheet for IMX477. Could you kindly provide me with the full datasheet for IMX477, including detailed registers?

Thank you,
Huy Le

**Comment by 6by9** [comment]
Whilst the comment didn't get copied from imx219_modes.h into imx477_modes.h, I'm afraid it is also valid for imx477
https://github.com/raspberrypi/raspiraw/blob/master/imx219_modes.h#L29-L35

The datasheet is under NDA, so we can not distribute it.

**Comment by 6by9** [comment]
FWIW unrelated to this I've just been tweaking IMX477 settings for Pi5. 

https://github.com/raspberrypi/linux/pull/6208 results in a 1332x990 raw10 mode that should be able to achieve 254fps. I provide no guarantees of compatibility with the Jetson though.
