### ISSUE TITLE
Pi 2B 1.2 not recognised by camera_i2c

### ISSUE THREAD

**Issue by tmorley2000** [6by9/raspiraw#9]
A recent Pi 2B 1.2 isn't recognised by camera_i2c

`tim@picam2:~/raspiraw/raspiraw $ ./camera_i2c
setting GPIO for board revsion: a02042
Failed: don't know how to set GPIO for this board!
`

**Comment by 6by9** [comment]
Commit pushed that hopefully sets things up appropriately (I haven't got one to test).

**Comment by tmorley2000** [comment]
Wonderful, works nicely!
